# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '知乎日报' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 知乎日报

  pod 'FTIndicator'#弹窗
  pod 'Kingfisher'#网络图片

end
